save point

diff --git a/sim/runSimulator b/sim/runSimulator
--- a/sim/runSimulator
+++ b/sim/runSimulator
@@ -4,11 +4,14 @@ set -e
 
 cleanup() {
     exitCode=$?
-    provisioner --terminate || true
+
+    if [ "$killBox" == "true" ]; then
+      provisioner --terminate || true
+    fi
 
     hear=$(pwd | grep -oh workspace.*)
     echo http://54.87.52.100/~jenkins/${hear}
-    if (( $exitCode != 0 )) ; then 
+    if (( $exitCode != 0 )) ; then
       slackPost simulator-fail FAIL \<http://54.87.52.100/~jenkins/${hear}\>
     fi
     exit $exitCode
@@ -27,17 +30,18 @@ testDir=""
 hazelcastVersion="master"
 simulatorVersion='master'
 lab="false"
+killBox="true"
 
-OPTS=`getopt -o : --long  boxCount:,memberBox:,members:,clients:,duration:,ee:,machienSpec:,testDir:,hazelcastVersion:,simulatorVersion:,lab: -n 'parse-options' -- "$@"` || { echo "Failed parsing options." >&2 ; exit 1; }
+OPTS=`getopt -o : --long  boxCount:,memberBox:,members:,clients:,duration:,ee:,machienSpec:,testDir:,hazelcastVersion:,simulatorVersion:,lab:,killBox: -n 'parse-options' -- "$@"` || { echo "Failed parsing options." >&2 ; exit 1; }
 
-initCmdArgs () { 
+initCmdArgs () {
  eval set -- "$OPTS"
-  
+
  while true; do
   case "$1" in
     --ee ) ee="$2"; shift 2 ;;
     --boxCount ) boxCount="$2"; shift 2 ;;
-    --memberBox ) memberBox="$2"; shift 2 ;; 
+    --memberBox ) memberBox="$2"; shift 2 ;;
     --members ) members="$2"; shift 2 ;;
     --clients ) clients="$2"; shift 2 ;;
     --duration ) duration="$2"; shift 2  ;;
@@ -46,6 +50,7 @@ initCmdArgs () {
     --hazelcastVersion ) hazelcastVersion="$2"; shift 2  ;;
     --simulatorVersion ) simulatorVersion="$2"; shift 2  ;;
     --lab ) lab="$2"; shift 2 ;;
+    --killBox ) killBox="$2"; shift 2 ;;
     -- ) shift; break ;;
     * ) break ;;
   esac
@@ -55,8 +60,8 @@ initCmdArgs () {
 updateRepos () {
  update-simulator ${simulatorVersion}
  update-hazelcast ${hazelcastVersion}
-      
- if [ "$ee" == "true" ]; then 
+
+ if [ "$ee" == "true" ]; then
     update-hazelcast-ee ${hazelcastVersion} build
  fi
 
@@ -81,7 +86,7 @@ setSimulatorProps () {
 
  if [ "$lab" == "true" ]; then
    cp -fr ~/lab/. .
- fi 
+ fi
 
  hzVersion=$(getHazelcastVersion)
  sed -i s/maven=.*/maven="${hzVersion}"/ simulator.properties
@@ -110,4 +115,5 @@ mainFunction () {
  exit $exitCode
 }
 
-mainFunction 
+mainFunction
+
diff --git a/sim/setupSimTestProfile b/sim/setupSimTestProfile
--- a/sim/setupSimTestProfile
+++ b/sim/setupSimTestProfile
@@ -1,59 +1,62 @@
 #!/usr/bin/env bash
 
-duration=${1:-48h}
+duration=$1
 
-profile=$(getHazelcastVersion)
-echo "version to test ${profile}"
+if [ $# -eq 0 ]; then
+    echo "duration required e.g:  5m 6h 48h"; exit 1
+fi
 
-declare -a clusterProfileList=("test" "small" "medium" "large" "xlarge")
-boxCount=0
-memberBox=0
-members=0
-clients=0
 
-for clusterProfile in "${clusterProfileList[@]}" 
-do
-	case $clusterProfile in
-	    test)
-        	boxCount=2
-	        members=2
-        	clients=2
-        	;;
-	    small)
-	        boxCount=4
-	        members=4
-	        clients=8
-	        ;;
-	    medium)
-	        boxCount=6
-	        members=6
-	        clients=24
-	        ;;
-	    large)
-	        boxCount=10
-	        members=10
-	        clients=50
-	        ;;
-	    xlarge)
-	        boxCount=25
-	        members=25
-	        clients=100
-	        ;;
-	    *)
-	        echo "Unknown cluster size"
-	        exit 1
-	esac
+hzVersion=$(getHazelcastVersion)
+echo "version to test ${hzVersion}"
 
-	mkdir -p ${profile}/${clusterProfile}
+function setup {
 
-	cp ${SIMULATOR_HOME}/simulator-tests/test.properties ${profile}/${clusterProfile}/
-        cp ~/configuration/simulator.properties ${profile}/${clusterProfile}/
-        cp ~/configuration/run ${profile}/${clusterProfile}/
+ ee=$1
+ boxCount=$2
+ memberBox=$3
+ members=$4
+ clients=$5
+ clusterProfile=$6
+ 
+ startBox=$7
+ endBox=$8
 
-	sed -i s/'boxCount=$1'/boxCount=${boxCount}/g ${profile}/${clusterProfile}/run
-        sed -i s/'memberBox=$2'/memberBox=${memberBox}/g ${profile}/${clusterProfile}/run
-	sed -i s/'members=$3'/members=${members}/g ${profile}/${clusterProfile}/run
-	sed -i s/'clients=$4'/clients=${clients}/g ${profile}/${clusterProfile}/run
-	sed -i s/'duration=$5'/duration=${duration}/g ${profile}/${clusterProfile}/run
-	sed -i s/'HAZELCAST_VERSION_SPEC=maven=???'/HAZELCAST_VERSION_SPEC=maven=${profile}/g ${profile}/${clusterProfile}/simulator.properties
-done
+        local="${hzVersion}/${ee}/${clusterProfile}"
+    	mkdir -p ${local}
+        cp ${SIMULATOR_HOME}/simulator-tests/test.properties ${local}/
+        cp ~/configuration/simulator.properties ${local}/
+        cp ~/configuration/run ${local}/
+
+        if [ "$ee" == "ee" ]; then
+          cp -fr $SIM_EE_TEST_DIR/ee-simulator-tests/. ${local}/
+        fi
+  
+	sed -i s/'boxCount=$1'/boxCount=${boxCount}/g ${local}/run
+        sed -i s/'memberBox=$2'/memberBox=${memberBox}/g ${local}/run
+	sed -i s/'members=$3'/members=${members}/g ${local}/run
+	sed -i s/'clients=$4'/clients=${clients}/g ${local}/run
+	sed -i s/'duration=$5'/duration=${duration}/g ${local}/run
+
+          sed -i s/'ee=$6'/ee=false/g ${local}/run
+
+        if [ "$ee" == "ee" ]; then
+          sed -i s/'ee=$6'/ee=true/g ${local}/run
+	fi
+
+        if [ "$clusterProfile" == "lab" ]; then
+          cp ~/lab/* ${local}/
+          sed -i -n ${startBox},${endBox}p ${local}/agents.txt
+        fi
+
+        sed -i s/'HAZELCAST_VERSION_SPEC=maven=???'/HAZELCAST_VERSION_SPEC=maven=${hzVersion}/g ${local}/simulator.properties
+}
+
+setup  os  4   0  4   8    small
+setup  os  10  0  10  50   large
+setup  os  25  0  25  100  xlarge
+
+setup  ee  4   0  4   8    small
+setup  ee  10  0  10  50   large
+setup  ee  25  0  25  100  xlarge
+setup  ee  7   0  7   700  lab 1 7
